//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONMUA
    {
        public int MaDonMua { get; set; }
        public int MaLSP { get; set; }
        public string HinhMinhHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string AnhMinhHoa { get; set; }
        public string MauSac { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
    
        public virtual DONMUASP DONMUASP { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
