//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.LOAISANPHAMs = new HashSet<LOAISANPHAM>();
            this.FEEDBACKs = new HashSet<FEEDBACK>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string HinhMinhHoa { get; set; }
        public string DungLuong { get; set; }
        public decimal DonGia { get; set; }
        public string CPU { get; set; }
        public string ManHinh { get; set; }
        public string RAM { get; set; }
        public string UuDai { get; set; }
        public Nullable<int> XepHangSao { get; set; }
        public string DanhGia { get; set; }
        public string DiemThuong { get; set; }
        public string MauSac { get; set; }
        public string CameraTruoc { get; set; }
        public string CameraSau { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public string HangDienThoai { get; set; }
    
        public virtual DANHMUC DANHMUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAISANPHAM> LOAISANPHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEEDBACK> FEEDBACKs { get; set; }
    }
}
